// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MainBottom: typeof import('./src/components/mainpage/MainBottom.vue')['default']
    MainCardItem: typeof import('./src/components/mainpage/MainCardItem.vue')['default']
    MainCardList: typeof import('./src/components/mainpage/MainCardList.vue')['default']
    MainCenter: typeof import('./src/components/mainpage/MainCenter.vue')['default']
    MyData: typeof import('./src/components/mypage/MyData.vue')['default']
    MyDelete: typeof import('./src/components/mypage/MyDelete.vue')['default']
    MyHeader: typeof import('./src/components/common/MyHeader.vue')['default']
    MyMain: typeof import('./src/components/mypage/MyMain.vue')['default']
    MyModify: typeof import('./src/components/mypage/MyModify.vue')['default']
    MyPwdCheck: typeof import('./src/components/mypage/MyPwdCheck.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
