INSERT INTO user (ID, USERNAME, PASSWORD, NICKNAME, ACTIVATED) VALUES (1, 'admin', '$2ai', 'admin', 1);
# INSERT INTO USER_AUTHORITY (ID, AUTHORITY_NAME) values (1, 'ROLE_ADMIN');
# # INSERT INTO USER_AUTHORITY (ID, AUTHORITY_NAME) values (1, 'ROLE_USER');
#
# INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_ADMIN');
# INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_USER');


